/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_MantenimientoCursos;
import modelo.MetodosConexionBD;

/**
 *
 * @author JorgeIgnacio
 */
public class FRM_MantenimientoCursos extends javax.swing.JFrame {

    //Referencias
    Controlador_FRM_MantenimientoCursos cfrmmc;
    MetodosConexionBD mcbd;
    
    public FRM_MantenimientoCursos(MetodosConexionBD mcbd) {
        initComponents();
        this.mcbd = mcbd;
        cfrmmc = new Controlador_FRM_MantenimientoCursos(this, this.mcbd);
        this.gUI_Botones2.agregarEventosCurso(cfrmmc);
    }
    
    /*
    
    */
    public String[] devolverInformacion() {
        
        return this.gUI_InformacionCurso2.devolverInformacion();
        
    }//Fin devolverInformacion
    
    /*
    
    */
    public void limpiarCampos() {
        
        this.gUI_InformacionCurso2.limpiarCampos();
        
    }//Fin limpiarCampos

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionCurso2 = new vista.GUI_InformacionCurso();
        gUI_Botones2 = new vista.GUI_Botones();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gUI_InformacionCurso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gUI_Botones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_InformacionCurso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gUI_Botones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.GUI_Botones gUI_Botones2;
    private vista.GUI_InformacionCurso gUI_InformacionCurso2;
    // End of variables declaration//GEN-END:variables
}
