/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_MenuPrincipal;
import modelo.MetodosConexionBD;

/**
 *
 * @author JorgeIgnacio
 */
public class FRM_MenuPrincipal extends javax.swing.JFrame {

    //Referencias
    Controlador_FRM_MenuPrincipal cfrmmp;
    
    public FRM_MenuPrincipal() {
        
        initComponents();
        cfrmmp = new Controlador_FRM_MenuPrincipal();
        agregarEventos();
        
    }
    
    public void agregarEventos() {
        
        this.jMenuItem_Estudiante.addActionListener(cfrmmp);
        this.jMenuItem_Curso.addActionListener(cfrmmp);
        this.jMenuItem_Matricula.addActionListener(cfrmmp);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar_Principal = new javax.swing.JMenuBar();
        jM_Archivo = new javax.swing.JMenu();
        jM_Mantenimiento = new javax.swing.JMenu();
        jMenuItem_Estudiante = new javax.swing.JMenuItem();
        jMenuItem_Curso = new javax.swing.JMenuItem();
        jMenu_Matricula = new javax.swing.JMenu();
        jMenuItem_Matricula = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jM_Archivo.setText("Archivo");
        jMenuBar_Principal.add(jM_Archivo);

        jM_Mantenimiento.setText("Mantenimiento");

        jMenuItem_Estudiante.setText("Mantenimiento Estudiantes");
        jMenuItem_Estudiante.setActionCommand("Mantenimiento Estudiante");
        jM_Mantenimiento.add(jMenuItem_Estudiante);

        jMenuItem_Curso.setText("Mantenimiento Curso");
        jM_Mantenimiento.add(jMenuItem_Curso);

        jMenuBar_Principal.add(jM_Mantenimiento);

        jMenu_Matricula.setText("Matrícula");

        jMenuItem_Matricula.setText("Matrícula");
        jMenuItem_Matricula.setActionCommand("Matricula");
        jMenu_Matricula.add(jMenuItem_Matricula);

        jMenuBar_Principal.add(jMenu_Matricula);

        setJMenuBar(jMenuBar_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jM_Archivo;
    private javax.swing.JMenu jM_Mantenimiento;
    private javax.swing.JMenuBar jMenuBar_Principal;
    private javax.swing.JMenuItem jMenuItem_Curso;
    private javax.swing.JMenuItem jMenuItem_Estudiante;
    private javax.swing.JMenuItem jMenuItem_Matricula;
    private javax.swing.JMenu jMenu_Matricula;
    // End of variables declaration//GEN-END:variables
}
