/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_MantenimientoEstudiantes;
import modelo.MetodosConexionBD;

/**
 *
 * @author JorgeIgnacio
 */
public class FRM_MantenimientoEstudiantes extends javax.swing.JFrame {

    //Referencias
    Controlador_FRM_MantenimientoEstudiantes cfrmme;
    MetodosConexionBD mcbd;
    
    public FRM_MantenimientoEstudiantes(MetodosConexionBD mcbd) {
        initComponents();
        //Instancias
        this.mcbd = mcbd;
        cfrmme = new Controlador_FRM_MantenimientoEstudiantes(this, this.mcbd);
        this.gUI_Botones1.agregarEventosEstudiate(cfrmme);
    }
    
    /*
    
    */
    public String[] obtenerInformacion() {
        
        return this.gUI_InformacionEstudiante1.obtenerInformacion();
        
    }//Fin obtenerInforacion
    
    /*
    
    */
    public void mostrarInformacion(String arregloInformacion[]) {
        
        this.gUI_InformacionEstudiante1.mostrarInformacion(arregloInformacion);
        
    }//Fin mostrarInformacion
    
    /*
    
    */
    public void limpiarCampos() {
        
        this.gUI_InformacionEstudiante1.limpiarCampos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new vista.GUI_Botones();
        gUI_InformacionEstudiante1 = new vista.GUI_InformacionEstudiante();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_InformacionEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_InformacionEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.GUI_Botones gUI_Botones1;
    private vista.GUI_InformacionEstudiante gUI_InformacionEstudiante1;
    // End of variables declaration//GEN-END:variables
}
