/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_MantenimientoCursos;
import controlador.Controlador_FRM_MantenimientoEstudiantes;
import controlador.Controlador_FRM_Matricula;

/**
 *
 * @author JorgeIgnacio
 */
public class GUI_Botones extends javax.swing.JPanel {

    //Referencias
    Controlador_FRM_MantenimientoEstudiantes cfrmme;
    Controlador_FRM_MantenimientoCursos cfrmmc;
    Controlador_FRM_Matricula cfrmm;
    
    //Constructor
    public GUI_Botones() {
        initComponents();
        //Instancias
    }
    
    /*
    
    */
    public void agregarEventosEstudiate(Controlador_FRM_MantenimientoEstudiantes cfrmme) {
        
        this.cfrmme = cfrmme;
        this.jB_Consultar.addActionListener(cfrmme);
        this.jB_Agregar.addActionListener(cfrmme);
        this.jB_Modificar.addActionListener(cfrmme);
        this.jB_Eliminar.addActionListener(cfrmme);
        
    }//Fin agregarEventos
    
    /*
    
    */
    public void agregarEventosCurso(Controlador_FRM_MantenimientoCursos cfrmmc) {
        
        this.cfrmmc = cfrmmc;
        this.jB_Consultar.addActionListener(cfrmmc);
        this.jB_Agregar.addActionListener(cfrmmc);
        this.jB_Modificar.addActionListener(cfrmmc);
        this.jB_Eliminar.addActionListener(cfrmmc);
        
    }//Fin agregarEventosCurso
    
    /*
    
    */
    public void agregarEventosMatricula(Controlador_FRM_Matricula cfrmm) {
        
        this.cfrmm = cfrmm;
        this.jB_Consultar.addActionListener(cfrmm);
        this.jB_Agregar.addActionListener(cfrmm);
        this.jB_Modificar.addActionListener(cfrmm);
        this.jB_Eliminar.addActionListener(cfrmm);
        
    }//agregarEventosMatricula
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_Consultar = new javax.swing.JButton();
        jB_Agregar = new javax.swing.JButton();
        jB_Modificar = new javax.swing.JButton();
        jB_Eliminar = new javax.swing.JButton();

        jB_Consultar.setText("CONSULTAR");

        jB_Agregar.setText("AGREGAR");

        jB_Modificar.setText("MODIFICAR");

        jB_Eliminar.setText("ELIMINAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jB_Consultar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jB_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jB_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jB_Modificar)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Consultar)
                    .addComponent(jB_Modificar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Agregar)
                    .addComponent(jB_Eliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Agregar;
    private javax.swing.JButton jB_Consultar;
    private javax.swing.JButton jB_Eliminar;
    private javax.swing.JButton jB_Modificar;
    // End of variables declaration//GEN-END:variables
}
