/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author JorgeIgnacio
 */
public class GUI_InformacionEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionEstudiante
     */
    public GUI_InformacionEstudiante() {
        initComponents();
    }
    
    /*
    
    */
    public String[] obtenerInformacion() {
        
        String arregloInformacion[] = new String[3];
        
        arregloInformacion[0] = this.jT_Cedula.getText();
        arregloInformacion[1] = this.jT_Nombre.getText();
        arregloInformacion[2] = this.jT_Direccion.getText();
                
        return arregloInformacion;
        
    }//Fin obtenerInformacion
    
    /*
    
    */
    public void mostrarInformacion(String arregloInformacion[]) {
        
        this.jT_Nombre.setText(arregloInformacion[0]);
        this.jT_Direccion.setText(arregloInformacion[1]);
        
    }//Fin mostrarInformacion
    
    public void limpiarCampos() {
        
        this.jT_Cedula.setText("");
        this.jT_Nombre.setText("");
        this.jT_Direccion.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Nombre = new javax.swing.JLabel();
        jT_Cedula = new javax.swing.JTextField();
        jT_Nombre = new javax.swing.JTextField();
        jL_Cedula = new javax.swing.JLabel();
        jT_Direccion = new javax.swing.JTextField();
        jL_Direccion = new javax.swing.JLabel();

        jL_Nombre.setText("NOMBRE");

        jL_Cedula.setText("CEDULA");

        jL_Direccion.setText("DIRECCION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Direccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_Cedula)
                    .addComponent(jL_Nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jT_Nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jT_Direccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jT_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Cedula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Nombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Direccion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_Cedula;
    private javax.swing.JLabel jL_Direccion;
    private javax.swing.JLabel jL_Nombre;
    private javax.swing.JTextField jT_Cedula;
    private javax.swing.JTextField jT_Direccion;
    private javax.swing.JTextField jT_Nombre;
    // End of variables declaration//GEN-END:variables
}
